<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KJ400B0" failures="1" tests="5" name="com.service.EmployeeServiceTest" time="0.014" errors="0" timestamp="2022-11-06T20:32:09 IST" skipped="0">
  <testcase classname="com.service.EmployeeServiceTest" name="getAllEmployeeTest" time="0.002"/>
  <system-out/>
  <testcase classname="com.service.EmployeeServiceTest" name="getEmployeeTest" time="0.003"/>
  <system-out/>
  <testcase classname="com.service.EmployeeServiceTest" name="searchEmployeeTest" time="0.003"/>
  <system-out/>
  <testcase classname="com.service.EmployeeServiceTest" name="updateSalaryTest" time="0.003">
    <failure message="expected [48600.0] but found [48000.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [48600.0] but found [48000.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEquals(Assert.java:844)
at org.testng.Assert.assertEquals(Assert.java:879)
at com.service.EmployeeServiceTest.updateSalaryTest(EmployeeServiceTest.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- updateSalaryTest -->
  <system-out/>
  <testcase classname="com.service.EmployeeServiceTest" name="removeEmployeeTest" time="0.003"/>
  <system-out/>
</testsuite> <!-- com.service.EmployeeServiceTest -->
